pipeline {
    agent {
        node {
            label 'docker-agent-python'
        }
    }
    environment {
        NAME = 'Toro'
    }
    triggers {
        pollSCM '* * * * *'
    }

    stages {
        stage('Checkoout') {
            steps {
                git 'https://github.com/kennytoro/python_files.git'
            }
        }

        stage('Build') {
            steps {
                echo "$NAME is building"
                sh '''
                ls
                python3 First.py
                echo "doing stuffs"
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo "kubectl apply -f ."
            }
        }
    }

}